export const INITIALIZE_SHOWS = "INITIALIZE_SHOWS";
export const INFINITE_SCROLL_FETCH_SHOW_DATA =
  "INFINITE_SCROLL_FETCH_SHOW_DATA";
export const UPDATE_SHOWS = "UPDATE_SHOWS";
export const FETCH_SHOW_DATA = "FETCH_SHOW_DATA";
export const FETCHED_SHOW_DATA = "FETCHED_SHOW_DATA";
export const FETCH_SEARCH_SHOW_DATA = "FETCH_SEARCH_SHOW_DATA";
export const FETCHED_SEARCH_SHOW_DATA = "FETCHED_SEARCH_SHOW_DATA";
export const FETCH_EPISODE_DATA = "FETCH_EPISODE_DATA";
export const FETCHED_EPISODE_DATA = "FETCHED_EPISODE_DATA";
export const FETCH_SEASON_DATA = "FETCH_SEASON_DATA";
export const FETCHED_SEASON_DATA = "FETCHED_SEASON_DATA";
export const UPDATE_SHOW_DATA = "UPDATE_SHOW_DATA";
